### ISSUE TITLE
[FEAT] Add hacktoberfest topic

### ISSUE THREAD

**Issue by vedantmgoyal9** [App-Choreography/Dev-Dictionary#5]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

[Hacktoberfest](https://hacktoberfest.com/) is back this year. I think we should participate in this.

**Describe alternatives you've considered**

**Additional context**

**Comment by NS007-dev** [comment]
@vedantmgoyal2009 Thank you for opening this issue!
I had signed this org and myself (as a maintainer and participant) up to hacktoberfest.
However there is only 4 days of Hacktoberfest left.
I think we should leave it for this year, and once this org becomes busy, it should be ready for events such as Hacktoberfest.
I really appreciate all your help and support in this org!

**Comment by NS007-dev** [comment]
@vedantmgoyal2009 in order for this to be part of Hacktoberfest, should I just add the hacktober-fest accepted tag to approved prs, and to the repos description?
Like So?:
![image](https://user-images.githubusercontent.com/70807500/198327445-a983468e-0da8-4ffd-9740-ff8f5019edd4.png)

**Comment by vedantmgoyal9** [comment]
It should be just "hacktoberfest".

**Comment by NS007-dev** [comment]
I just changed it to just 'hacktoberfest', and in PR #4 I tried adding the hacktoberfest-accepted tag.

**Comment by vedantmgoyal9** [comment]
That's good. If the contributor is participating in the Hacktoberfest, his PR would be counted then👍🏻
